name: "Daemon Planner"

on:
  workflow_dispatch:
    inputs:
      stateId:
        description: "State Id"
      eventName:
        description: "Event Name"
      eventPayload:
        description: "Event Payload"
      settings:
        description: "Settings"
      authToken:
        description: "Auth Token"
      ref:
        description: "Ref"
      signature:
        description: "The kernel signature"
      command:
        description: "Command from the Kernel"
        required: false

jobs:
  compute:
    name: "Daemon Planner"
    runs-on: ubuntu-latest
    permissions: write-all
    environment: ${{ (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')) && 'main' || 'development' }}
    env:
      PLUGIN_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      KERNEL_PUBLIC_KEY: ${{ secrets.KERNEL_PUBLIC_KEY }}
      MATCHMAKING_ENDPOINT: ${{ vars.MATCHMAKING_ENDPOINT }}
      START_STOP_ENDPOINT: ${{ vars.START_STOP_ENDPOINT }}
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      LOG_LEVEL: ${{ secrets.LOG_LEVEL || 'info' }}

    steps:
      - uses: actions/checkout@v6

      - name: execute directive
        run: node ./dist/index.js
